version: "3"

services:
  backend:
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./flaskr:/server

  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
